bedag/helm-charts

.kube-linter.yaml, charts/e2g/.kube-linter.yaml, charts/e2g/Chart.yaml, charts/e2g/README.md, charts/e2g/examples/simple.yaml, charts/e2g/templates/bundle.yaml, charts/e2g/templates/e2g.tpl, charts/e2g/values.yaml
Signed-off-by: Kevin Klopfenstein <kk@sudo-i.net>
- adding filtergroups
- exclude use-namespace from kube-linter global
- bump e2g
- fixes #57 
**Checklist**:
=> [e2g]: adding filtergroups

charts/manifests/Chart.yaml, charts/manifests/README.md, charts/manifests/templates/manifests/_podDisruptionBudget.tpl
Signed-off-by: Adrian Berger <adrian.berger@bedag.ch>
Adds new PodDisruptionBudget api v1:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
Since we don't have the possibility to add empty selector field, this is not a breaking change.
**Checklist**:
=> [manifest]: Add PodDisruptionBudget v1 to manifest helm chart

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_deployment.yaml, charts/common/templates/_pod.yaml
- fix usage of controller replica with count 0 (e.g. value `components.backend.controller.replicas: 0`)
- fix volumemount of binaryfiles
- replicas: see https://github.com/helm/helm/issues/3164#issuecomment-636267669
- binaryfile: see https://github.com/bedag/helm-charts/blob/master/charts/common/templates/_binaryfiles.yaml#L15
**Checklist**:
=> [common]: fix controller replica count for zero & binaryfile volumemount

charts/common/Chart.yaml, charts/common/README.md, charts/common/README.md.gotmpl, charts/common/ci/values.test.yaml, charts/common/templates/_networkpolicy-sections.yaml, charts/common/templates/_networkpolicy.yaml, charts/common/values.schema.json, charts/common/values.yaml
- Add the possibility to create multiple networkpolicies
- Add the possibility to use namespaceSelector in ingress and egress.
**Checklist**:
=> [common]: add egress and namespaceSelector in networkpolicy

charts/common/Chart.yaml, charts/common/README.md, charts/common/ci/values.test.yaml, charts/common/templates/_pod.yaml, charts/common/values.yaml
Add possibility to add emptyDir volumes in pod definition.
**Checklist**:
=> [common]: add emptyDir volumes

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/lifecycle/extra-manifests.yaml, charts/vcluster/templates/pkg/_images.tpl
creds.username and creds.password were never reachable, therefor both values were `nil`
**Checklist**:
=> fix(vcluster): correctly template dockerconfig

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/components/kubernetes/apiserver/probe.yaml, charts/vcluster/templates/components/kubernetes/etcd/servicemonitor.yaml, charts/vcluster/templates/pkg/_components.tpl, charts/vcluster/values.yaml
This PR adds the possibility to create a Probe resource for the k8s apiserver, which allows to monitor if the apiserver is responding as expected
- 
**Checklist**:
=> [vcluster]: Add k8s apiserver probe resource

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_pod.yaml, charts/common/values.schema.json, charts/common/values.yaml
=> [common]: Add ability to set defaultMode for all configFiles

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_container.yaml, charts/common/values.schema.json, charts/common/values.yaml
Allows to specify custom `envFrom` for all container components.
**Checklist**:
=> [common]: add envfrom

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_cronjob.yaml, charts/common/templates/_deployment.yaml, charts/common/templates/_statefulset.yaml, charts/common/templates/helpers/_labels.tpl
=> [common]: add tpl for labels and annotations

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_pod.yaml, charts/common/values.schema.json, charts/common/values.yaml
Makes the pullSecret configurable in order to use the same secret for multiple common helm chart instances.
**Checklist**:
=> [common]: Make pullSecret configurable

charts/common/Chart.yaml, charts/common/README.md, charts/common/ci/values.test.yaml, charts/common/templates/includes.yaml, charts/common/values.schema.json, charts/common/values.yaml
Add the possibility to activate includes as values.
This eliminates the need to create umbrella charts to use the common chart, yet it can still be used as a library chart.
**Checklist**:
=> [common] includes as values

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/pkg/_common.tpl
Removes the bash variable KUBERNETES_SERVICE_HOST from the no_proxy construct, which is causing issue with machine-controller / osn
**Checklist**:
=> [vcluster]: Removing variable 'KUBERNETES_SERVICE_HOST' from no_proxy

charts/common/Chart.yaml, charts/common/README.md, charts/common/ci/values.test.yaml, charts/common/templates/_binaryfiles.yaml, charts/common/templates/_configfiles.yaml, charts/common/templates/_configmap.yaml, charts/common/templates/_deployment.yaml, charts/common/templates/_pod.yaml, charts/common/templates/_secret.yaml, charts/common/templates/_statefulset.yaml
According to sprig documentation, our merge was used wrong way.  
Sprig documentation: https://github.com/Masterminds/sprig/blob/master/docs/dicts.md#merge-mustmerge  
**Which issue this PR fixes**
With this merge, we fix issues resulting from InitContainer being merged into Containers (ie. InitContainers appear twice)  
fixes #123 
**Checklist**:
=> [common]: fix duplicated init container

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_servicemonitor-servicemonitor.yaml, charts/common/templates/includes.yaml, charts/common/values.schema.json, charts/common/values.yaml
* Add new spec for setting the `scrapeTimeout` in a serviceMonitor endpoint
* Fix/change includes
**Checklist**:
=> [common]: Add scrapeTimeout to serviceMonitor endpoints & fix inclusion of components

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/components/kubernetes/etcd/backup-job.yaml
The indentation for some values is wrong for the etcd backup job.  
This PR fixes these
**Checklist**:
=> [vcluster]: fix some etcd backup job values werde not intended correctly

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/components/kubernetes/apiserver/probe.yaml
Currently when enabling probes for the apiServer, the value for proxyUrl is `nil` instead of an empty string.
```
kubectl explain probes.monitoring.coreos.com.spec.prober.proxyUrl
GROUP:      monitoring.coreos.com
KIND:       Probe
VERSION:    v1
FIELD: proxyUrl <string>
DESCRIPTION:
Optional ProxyURL.
```
**Checklist**:
=> [vcluster]: Template empty string instead of nil

charts/common/Chart.yaml, charts/common/README.md, charts/common/ci/values.test.yaml, charts/common/templates/_pod.yaml, charts/common/values.schema.json, charts/common/values.yaml
- Adds option to  [Adding entries to Pod /etc/hosts with HostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/)
**Checklist**:
=> [common]: enable host aliases in common chart

charts/common/Chart.yaml, charts/common/README.md, charts/common/README.md.gotmpl, charts/common/templates/_ingress-ingress.yaml, charts/common/templates/_ingress-secret.yaml, charts/common/values.schema.json, charts/common/values.yaml
**What this PR does**: This PR enhances the common chart with the ability to include multiple ingress objects, e.g. to have different annotations
**Checklist**:
=> [common]: making multiple ingress objects possible

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/components/kubernetes/apiserver/deployment.yaml
Adds the release name as a prefix to the audit logs in case multiple vclusters are running on the same node in order to avoid writing to the same file.
**Checklist**:
=> [vcluster]: add release name to audit logs as prefix

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/addons/scripts/configure-vcluster.sh
https://docs.cilium.io/en/v1.14/operations/upgrade/#deprecated-options
**Checklist**:
=> [vcluster]: switch kubeProxyReplacement to true instead of deprecated strict

charts/common/Chart.yaml, charts/common/README.md, charts/common/README.md.gotmpl, charts/common/templates/_ingress-ingress.yaml, charts/common/templates/_ingress-secret.yaml, charts/common/values.schema.json, charts/common/values.yaml
**What this PR does**: This PR enhances the common chart with the ability to define multiple hosts (with and without existing secrets) for one single ingress.
**Checklist**:
=> [common]: support for defining multiple hosts for an Ingress

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/addons/scripts/configure-current.sh, charts/vcluster/addons/scripts/configure-vcluster.sh, charts/vcluster/templates/components/kubernetes/kubeadm-config.yaml, charts/vcluster/templates/extra-manifests.yaml, charts/vcluster/values.yaml
- Disable autoscaler
- Fix reference of `.controlPlane.endpoint`
- Fix indentation in `charts/vcluster/templates/extra-manifests.yaml`
- Add `extraOnlineManifests` & `extraOnlineManifestsOnInstall` for vclusters
**Checklist**:
=> [vcluster]: llow installation of online manifests, disable autoscaler as default, remove unused values & fix references

.github/workflows/lint-and-test.yml, .pre-commit-config.yaml, Makefile, charts/vcluster/Chart.yaml, charts/vcluster/README.md, ct.yaml
=> [vcluster]: chore - switch dependency to oci helm chart

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/addons/scripts/configure-vcluster.sh
Only using kubectl apply can result in an error if the changes are too big:
`The CustomResourceDefinition "thanosrulers.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`
**Checklist**:
=> [vcluster]: fix - use ServerSideApply for lifecycle tasks

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/addons/scripts/configure-vcluster.sh
extraOnlineManifests was only triggered onInstall.
extraOnlineManifestsOnInstall was triggered everytime.
This is fixed with this PR.
Additionally the job doesn't fail if the command is failing, since we're redirecting the STDERR to /dev/null and return always a zero exit code with || true.
**Checklist**:
=> [vcluster]: fix - vcluster lifecycle tasks

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/helpers/_labels.tpl, charts/common/values.schema.json, charts/common/values.yaml
Adds optional value "_appVersion_" to override "_Chart.AppVersion_" in label "_app.kubernetes.io/version_"
**Checklist**:
=> [common]: appVersion available as optional value

charts/common/Chart.yaml, charts/common/README.md, charts/common/README.md.gotmpl, charts/common/templates/_pod.yaml, charts/common/values.schema.json, charts/common/values.yaml
This changes allows mounting existing configmaps as volumes.
**Checklist**:
=> [common]: Enable mounting of existing cm

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_pod.yaml, charts/common/values.schema.json, charts/common/values.yaml
Enable mounting of existing secrets and enable optional flag when mounting an existing ressources.
[https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist)
mostly copied from: [https://github.com/bedag/helm-charts/pull/147](https://github.com/bedag/helm-charts/pull/147) 
**Checklist**:
=> [common]: Enable mounting of existing secrets

charts/common/Chart.yaml, charts/common/README.md, charts/common/templates/_pvcs.yaml, charts/common/values.schema.json, charts/common/values.yaml
Allows setting annotations for PVCs. This is needed to set `helm.sh/resource-policy: keep` via the Helm Chart.
resolves: #135 
**Checklist**:
=> [common]: enable annotations for pvcs

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/components/kubernetes/_templates.tpl, charts/vcluster/templates/components/kubernetes/etcd/cleanup-job.yaml, charts/vcluster/templates/components/kubernetes/etcd/statefulset.yaml, charts/vcluster/templates/pkg/_common.tpl, charts/vcluster/templates/pkg/_images.tpl, charts/vcluster/values.yaml
- Update etcd image from `3.5.7-0` to `3.5.21-0`
- Update etcd livenessProbe to `/livez` endpoint
- Make etcd livenessProbe options configurable
- Add etcd readinessProbe (`/readyz`)
- Make etcd endpoints available through service dns instead of list of pod dns
- Add cleanup CronJob for etcd backups
- Fix typo in proxy envs injection
- Fix typos & spelling in `values.yaml` & `README.md`
- Fix bugs in imagePullSecrets
**Checklist**:
=> [vcluster]: feat - etcd updates & etcd backup cleanup

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/ci/registry-mirrors.yaml, charts/vcluster/ci/registry-primary-only.yaml, charts/vcluster/ci/registry-secondary.yaml, charts/vcluster/templates/components/machine-controller/_templates.tpl, charts/vcluster/templates/components/machine-controller/deployment.yaml, charts/vcluster/templates/components/operating-system-manager/_templates.tpl, charts/vcluster/templates/components/operating-system-manager/deployment.yaml, charts/vcluster/templates/pkg/_images.tpl, charts/vcluster/values.yaml, ct.yaml
- Add option to provide additional pull registries
- Add option to set mirror registries to operating-system-manager
- Remove obsolete cli flags of machine-controller
- Enable chart-testing for vcluster
**Checklist**:
=> [vcluster]: add secondary pull registries, add mirror registries, remove obsolete cli flags, enable chart-testing

charts/vcluster/Chart.yaml, charts/vcluster/README.md, charts/vcluster/templates/components/autoscaler/hpa.yaml, charts/vcluster/templates/components/autoscaler/pdb.yaml, charts/vcluster/templates/components/kubernetes/apiserver/hpa.yaml, charts/vcluster/templates/components/kubernetes/apiserver/pdb.yaml, charts/vcluster/templates/components/kubernetes/controller-manager/hpa.yaml, charts/vcluster/templates/components/kubernetes/controller-manager/pdb.yaml, charts/vcluster/templates/components/kubernetes/etcd/defrag-job.yaml, charts/vcluster/templates/components/kubernetes/etcd/pdb.yaml, charts/vcluster/templates/components/kubernetes/scheduler/hpa.yaml, charts/vcluster/templates/components/kubernetes/scheduler/pdb.yaml, charts/vcluster/templates/components/machine-controller/hpa.yaml, charts/vcluster/templates/components/machine-controller/pdb.yaml, charts/vcluster/templates/components/operating-system-manager/hpa.yaml, charts/vcluster/templates/components/operating-system-manager/pdb.yaml, charts/vcluster/values.yaml
- Remove helm chart dependency bitnami/common
- Adds optional etcd defragmentation CronJob as suggested in https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#cluster-defragmentation
Based on etcd-defrag: https://github.com/ahrtr/etcd-defrag
**Checklist**:
=> [vcluster]: remove bitnami common subchart, add optional etcd defragmentation CronJob
