.github/workflows/release.yml
README.md

Add Atrifactory Badge & Remove Documentation as Master Stage
**Checklist**:

Add Artifactory Badge

---

CODEOWNERS
charts/manifests/Chart.yaml
charts/manifests/README.md.gotmpl
charts/manifests/templates/manifests/README.md
charts/manifests/templates/utils/_internal.tpl
charts/manifests/templates/values/manifests/templates/_pvcTpl.yaml

Correct Manifests Link Path, Documentation Fixes
**Checklist**:

[manifests]: Correct Link Path

---

.gitignore

Signed-off-by: Bruno Jost <bruno.jost@bedag.ch>
**What this PR does**: extending .gitignore
**Checklist**:

extending .gitignore

---

charts/manifests/Chart.yaml

Add Annotations, Add Repository Verification
**Checklist**:

Verify as Publisher

---

charts/manifests/Chart.yaml
charts/manifests/templates/manifests/README.md
charts/manifests/templates/manifests/_daemonset.tpl
charts/manifests/templates/manifests/templates/_bundleExtras.tpl
charts/manifests/templates/values/manifests/_daemonset.yaml

Signed-off-by: kevin <kevin.klopfenstein@bedag.ch>
- adding daemonset 
#15 
**Checklist**:

[manifests] #15 adding daemonset

---

CONTRIBUTING.md
charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/_horizontalPodAutoscaler.tpl

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
manifests/hpa:
* Won't return manifest if empty metrics  
**Checklist**:

[manifests]: HPA requries metrics

---

CONTRIBUTING.md
charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/_cronjob.tpl

* manifests:
* **[Fixed]**: Cronjob render correct manifest structure
* **[Fixed]**: Cronjob use Default API `batch/v1beta1`
* housekeeping:
* Improved Changelog template  
**Checklist**:

[manifests]: Fixed Cronjob Bugs

---

CONTRIBUTING.md
charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/templates/_bundleExtras.tpl

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
Allows Secret Environment variable and service account, which include the pod values structure - not only deployments, sts and pods.
**Checklist**:

[manifests]: Fix BundleExtras & Contribution

---

charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/_cronjob.tpl
charts/manifests/templates/manifests/_ingress.tpl
charts/manifests/templates/values/manifests/_ingress.yaml

Ingress port name/number validation. Instead of converting every port value to DNS-1123 format, convert only if name was validated to DNS-1123 format.
**Checklist**:

[manifests]: Fix Ingress behvaior

---

CONTRIBUTING.md
charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/README.md.gotmpl
charts/manifests/templates/Quickstart.md
charts/manifests/templates/README.md
charts/manifests/templates/manifests/README.md
charts/manifests/templates/manifests/_deployment.tpl
charts/manifests/templates/manifests/templates/_containerTpl.tpl
charts/manifests/templates/presets/README.md
charts/manifests/templates/utils/README.md
charts/manifests/templates/utils/_environment.tpl

Correct inheritance for deployment values. Simplify environment rendering: Does no longer use a dedicated function but is directly in the container context executed. Documentation was moved to bundle, to illustrate usage of secret environment values.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
- fixes #27 
**Checklist**:

[manifests]: Deployment structure inheritance 

---

CONTRIBUTING.md
charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/_pod.tpl

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
Fixes duplicated `kind` entry for pod manifest.
**Checklist**:

[manifests]: Fix Pod Kind

---

CONTRIBUTING.md
charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/_pod.tpl

Trying to deploy Pods currently fails, because the metadata field is missing a name
```
Unable to continue with update: could not get information about the resource: resource name may not be empty
```
**Checklist**:

[manifests]: Add missing Pod Name

---

charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/_daemonset.tpl
charts/manifests/templates/manifests/_networkPolicy.tpl
charts/manifests/templates/manifests/_statefulset.tpl
charts/manifests/templates/manifests/templates/_podTpl.tpl
charts/manifests/templates/presets/components/_jmxexporter.tpl

bugfixing: change indent to nindent in some includes
**Checklist**:

[manifests]: fix: add newline indents

---

charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/README.md.gotmpl
charts/manifests/templates/Quickstart.md
charts/manifests/templates/README.md
charts/manifests/templates/manifests/README.md
charts/manifests/templates/manifests/_bundle.tpl
charts/manifests/templates/manifests/_cronjob.tpl
charts/manifests/templates/manifests/_daemonset.tpl
charts/manifests/templates/manifests/_deployment.tpl
charts/manifests/templates/manifests/_horizontalPodAutoscaler.tpl
charts/manifests/templates/manifests/_ingress.tpl
charts/manifests/templates/manifests/_job.tpl
charts/manifests/templates/manifests/_networkPolicy.tpl
charts/manifests/templates/manifests/_persistentVolumeClaim.tpl
charts/manifests/templates/manifests/_pod.tpl
charts/manifests/templates/manifests/_podDisruptionBudget.tpl
charts/manifests/templates/manifests/_service.tpl
charts/manifests/templates/manifests/_serviceAccount.tpl
charts/manifests/templates/manifests/_serviceMonitor.tpl
charts/manifests/templates/manifests/_statefulset.tpl
charts/manifests/templates/manifests/templates/_bundleExtras.tpl
charts/manifests/templates/manifests/templates/_containerTpl.tpl
charts/manifests/templates/manifests/templates/_jobTpl.tpl
charts/manifests/templates/manifests/templates/_podTpl.tpl
charts/manifests/templates/manifests/templates/_pvcTpl.tpl
charts/manifests/templates/utils/_common.tpl
charts/manifests/templates/utils/_intern.tpl
charts/manifests/templates/values/manifests/_service.yaml

This PR changes different sections of the manifests chart primarily to make it work with Helm 3.5.* releases. All major changes are documented in the Chart.yaml file of the manifests chart.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
* fixes #25 
**Checklist**:

[manifests]: Helm 3.5 Fixing

---

charts/manifests/Chart.yaml
charts/manifests/README.md.gotmpl
charts/manifests/templates/manifests/templates/_bundleExtras.tpl

Signed-off-by: kevin <kk@sudo-i.net>
* Chart Bump
* Always use merged Values & YAML Check merged Values
* Update Documentation
**Checklist**:

[manifests] bugfix missing overwrites

---

charts/manifests/Chart.yaml
charts/manifests/templates/Quickstart.md

Fixes a typo in charts/manifests/templates/Quickstart.md for generating values.
**Checklist**:

[Housekeeping] Fix parameter for generating statefulset values for frontend

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/testing.yml
charts/e2g/Chart.yaml
charts/e2g/README.md
charts/manifests/README.md
charts/manifests/README.md.gotmpl

Correct Workflow for helm-docs. Add Documentation for **e2g** Chart.
**Checklist**:

[housekeeping]: Auto Push Documentation

---

charts/kafdrop/.helmignore
charts/kafdrop/.kube-linter.yaml
charts/kafdrop/Chart.yaml
charts/kafdrop/README.md
charts/kafdrop/README.md.gotmpl
charts/kafdrop/templates/_kafdrop.tpl
charts/kafdrop/templates/bundle.yaml
charts/kafdrop/values.yaml
charts/kafdrop/values_production.yaml

Adds a publicly pullable chart for https://github.com/obsidiandynamics/kafdrop based on our manifests library.
**Checklist**:

[kafdrop]: Initial Chart Publish

---

CONTRIBUTING.md
charts/crowd/.helmignore
charts/crowd/.kube-linter.yaml
charts/crowd/Chart.yaml
charts/crowd/README.md
charts/crowd/README.md.gotmpl
charts/crowd/templates/NOTES.txt
charts/crowd/templates/_crowd.tpl
charts/crowd/templates/bundle.yaml
charts/crowd/values.yaml
charts/crowd/values_production.yaml
charts/crowd/values_standalone.yaml
scripts/helm-docs.sh

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
Releases first Version for the Crowd Helm Chart. Has been tested internally with data center mode. 
**Checklist**:

[crowd]: Release Crowd Helm Chart

---

charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/manifests/templates/_containerTpl.tpl
charts/manifests/templates/values/manifests/templates/_containerTpl.yaml

Signed-off-by: Jan Fuhrer <janfuhrer@mailbox.org>
**Checklist**:

[manifests]: add functionality for envFrom in containers

---

.github/workflows/pr-validate.yml
charts/e2g/Chart.yaml
charts/e2g/README.md
charts/e2g/templates/e2g.tpl

Signed-off-by: Kevin Klopfenstein <kevin.klopfenstein@bedag.ch>
- bump version of e2g
- bugfix: additional volume mounts
- bugfix: pr validation
**Checklist**:

[e2g]: additional volume mounts

---

charts/manifests/Chart.yaml
charts/manifests/README.md
charts/manifests/templates/values/manifests/_deployment.yaml

Fix link to docs in template.
**Checklist**:

[manifests]: fix link to deployment rollout strategy docs in deployment template

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/ci/values.test.yaml
charts/common/templates/helpers/_labels.tpl
charts/common/values.schema.json
charts/common/values.yaml

Signed-off-by: Jan Fuhrer <janfuhrer@mailbox.org>
- improve `values.schema.json` & ci test-values
- disable networkpolicy by default
**Checklist**:

[common]: Housekeeping

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/ci/values.test.yaml
charts/common/templates/_service.yaml
charts/common/values.yaml

Add Service Type LoadBalancer
**Checklist**:

[common]: Add Service Type Loadbalancer

---

charts/common/.helmignore
charts/common/Chart.yaml
charts/common/README.md
charts/common/ci/values.test.yaml
charts/common/templates/_networkpolicy.yaml
charts/common/values.schema.json

**What this PR does**: Fix linting of networkPolicy template
**Checklist**:

[common]: fix networkPolicy template for linting

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/values.schema.json

fix networkpolicy schema.json
**Checklist**:

[common]: fix networkpolicy schema.json

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/ci/values.test.yaml
charts/common/templates/_configfiles.yaml
charts/common/values.schema.json
charts/common/values.yaml

This will allow to create config files that are json formatted
**Checklist**:

[common]: allow json configFile

---

charts/vcluster/Chart.yaml
charts/vcluster/README.md
charts/vcluster/ci/lifecycle-values.yaml
charts/vcluster/templates/components/autoscaler/deployment.yaml
charts/vcluster/templates/components/autoscaler/servicemonitor.yaml
charts/vcluster/templates/components/kubernetes/admin-deployment.yaml
charts/vcluster/templates/components/kubernetes/apiserver-deployment.yaml
charts/vcluster/templates/components/kubernetes/controller-manager-deployment.yaml
charts/vcluster/templates/components/kubernetes/konnectivity-server-deployment.yaml
charts/vcluster/templates/components/kubernetes/scheduler-deployment.yaml
charts/vcluster/templates/components/machine-controller/deployment.yaml
charts/vcluster/templates/components/operating-system-manager/deployment.yaml
charts/vcluster/templates/lifecycle/cronjob.yaml
charts/vcluster/templates/lifecycle/job.yaml
charts/vcluster/values.yaml

fix: annotations and labels

---

charts/vcluster/Chart.yaml
charts/vcluster/README.md
charts/vcluster/manifests/kubernetes/konnectivity-agent.yaml

]vcluster]: fix correct agent port

---

charts/vcluster/Chart.yaml
charts/vcluster/README.md
charts/vcluster/README.md.gotmpl
charts/vcluster/templates/components/gitops/manifests.yaml
charts/vcluster/templates/components/kubernetes/etcd/backup-job.yaml
charts/vcluster/templates/components/kubernetes/etcd/backup-pvc.yaml
charts/vcluster/templates/components/kubernetes/etcd/certs.yaml
charts/vcluster/templates/components/kubernetes/etcd/service.yaml
charts/vcluster/templates/components/kubernetes/etcd/statefulset.yaml
charts/vcluster/templates/lifecycle/setup.yaml
charts/vcluster/values.yaml

[vcluster]: add etcd snapshot cronjob

---

charts/vcluster/Chart.yaml
charts/vcluster/README.md
charts/vcluster/addons/scripts/configure-current.sh
charts/vcluster/ci/kubeconfig-values.yaml
charts/vcluster/ci/lifecycle-values.yaml
charts/vcluster/templates/components/kubernetes/etcd/statefulset.yaml
charts/vcluster/templates/lifecycle/cronjob.yaml
charts/vcluster/templates/lifecycle/rbac.yaml
charts/vcluster/values.yaml

[vcluster]: fix argocd kubeconfig

---

charts/vcluster/Chart.yaml
charts/vcluster/README.md
charts/vcluster/ci/components-values.yaml
charts/vcluster/templates/components/kubernetes/apiserver/networkpolicy.yaml
charts/vcluster/templates/components/kubernetes/konnectivity/networkpolicy.yaml
charts/vcluster/templates/pkg/_components.tpl
charts/vcluster/values.yaml

[vcluster]: netpol support

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/templates/_cronjob.yaml
charts/common/templates/_deployment.yaml
charts/common/templates/_jobspec.yaml
charts/common/templates/_statefulset.yaml

fixes a missing quotation
\-
**Checklist**:

[common] fix: quote extraLabel value

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/templates/_pod.yaml
charts/common/values.yaml

Adds tjhe option to add existing external PVCs to the Pod.
**Checklist**:

[common] Add ability to add external pvcs to pods

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/templates/_pod.yaml
charts/common/values.yaml

**What this PR does**: It adds the volume type "csi" to the pod template.
**Checklist**:

[common]: add volume type csi

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/ci/values.test.yaml
charts/common/templates/_pod.yaml

**What this PR does**: fix rendering of csi volume -> #121 
**Checklist**:

[common]: fix rendering of csi volume

---

charts/vcluster/Chart.yaml
charts/vcluster/README.md
charts/vcluster/manifests/kubernetes/coredns.yaml
charts/vcluster/templates/components/autoscaler/deployment.yaml
charts/vcluster/templates/components/kubernetes/admin/deployment.yaml
charts/vcluster/templates/components/kubernetes/apiserver/deployment.yaml
charts/vcluster/templates/components/kubernetes/controller-manager/deployment.yaml
charts/vcluster/templates/components/kubernetes/etcd/backup-job.yaml
charts/vcluster/templates/components/kubernetes/etcd/statefulset.yaml
charts/vcluster/templates/components/kubernetes/konnectivity/deployment.yaml
charts/vcluster/templates/components/kubernetes/scheduler/deployment.yaml
charts/vcluster/templates/components/machine-controller/deployment.yaml
charts/vcluster/templates/components/operating-system-manager/deployment.yaml
charts/vcluster/templates/lifecycle/setup.yaml

- `nodeSelector` could not be specified per component
- `affinity` for coredns could not be specified
This PR fixes these issues.
**Checklist**:

[vcluster]: fix nodeSelector overrides for all components, fix: make affinity for coredns configurable

---

.github/workflows/lint-and-test.yml
.github/workflows/pr-label.yml
.github/workflows/pr-validate.yml
.github/workflows/release.yml

[workflow]: chore - update github workflows

---

charts/common/Chart.yaml
charts/common/README.md
charts/common/templates/_service.yaml

**Which issue this PR fixes**:
fixes #132
This can be used to close a PR that was already open. https://github.com/bedag/helm-charts/pull/131
**Checklist**:

[common]: Enable ClusterIP for all service types

---

.gitignore
charts/common/Chart.yaml
charts/common/README.md
charts/common/templates/_pod.yaml
charts/common/values.schema.json
charts/common/values.yaml

Add support for terminationGracePeriodSeconds.
**Checklist**:

[common]: add support for terminationGracePeriodSeconds
